# Generated by Django 5.0.6 on 2024-07-05 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_persona_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idplan', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('beneficios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FidelizacionPorProspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asociacion_inicio', models.DateField()),
                ('fecha_asociacion_final', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('canal_contacto', models.CharField(max_length=100)),
                ('notas', models.TextField()),
                ('valor_campana', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fidelizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fidelizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnombre', models.CharField(max_length=100)),
                ('idusuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='fidelizacionporprospecto',
            name='prospecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prospecto'),
        ),
    ]
